"""empty message

Revision ID: 417cdcd9c31a
Revises: None
Create Date: 2018-08-27 00:01:56.829984

"""

# revision identifiers, used by Alembic.
revision = '417cdcd9c31a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place', sa.String(), nullable=True),
    sa.Column('beacon1', sa.String(), nullable=True),
    sa.Column('beacon2', sa.String(), nullable=True),
    sa.Column('beacon3', sa.String(), nullable=True),
    sa.Column('beacon1x', sa.String(), nullable=True),
    sa.Column('beacon1y', sa.String(), nullable=True),
    sa.Column('beacon2x', sa.String(), nullable=True),
    sa.Column('beacon2y', sa.String(), nullable=True),
    sa.Column('beacon3x', sa.String(), nullable=True),
    sa.Column('beacon3y', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations')
    # ### end Alembic commands ###
