"""empty message

Revision ID: 5fc24910edb4
Revises: None
Create Date: 2018-08-22 21:51:58.861000

"""

# revision identifiers, used by Alembic.
revision = '5fc24910edb4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place', sa.String(), nullable=True),
    sa.Column('beacon1', sa.String(), nullable=True),
    sa.Column('beacon2', sa.String(), nullable=True),
    sa.Column('beacon3', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations')
    # ### end Alembic commands ###
