"""empty message

Revision ID: f51226794d59
Revises: None
Create Date: 2018-08-23 01:08:15.571247

"""

# revision identifiers, used by Alembic.
revision = 'f51226794d59'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('beacon1x', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('beacon1y', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('beacon2x', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('beacon2y', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('beacon3x', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('beacon3y', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'beacon3y')
    op.drop_column('locations', 'beacon3x')
    op.drop_column('locations', 'beacon2y')
    op.drop_column('locations', 'beacon2x')
    op.drop_column('locations', 'beacon1y')
    op.drop_column('locations', 'beacon1x')
    # ### end Alembic commands ###
